# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      - name: Process and Create Package Structure
        run: |
            sudo apt install r-cran-knitr graphviz imagemagick texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended
      - name: build package
        run: |
            make build pkg=sbi
            export VRS=`grep Version: sbi/DESCRIPTION | grep -oE '[.0-9]+'`
            echo "VRS=$VRS" >> $GITHUB_ENV
  
      - name: Upload Package Release files
        uses: actions/upload-artifact@v4
        with: 
          name: sbi_${{ env.VRS }}.tar.gz
          path: sbi_${{ env.VRS }}.tar.gz
